/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A distinguishable spreadsheet **error value** surfaced to Node.
 *
 * Returned in place of a `string` for any [`Value::Error`] (and the
 * unsupported [`Value::Ref`] case) so error results are never mistaken for a
 * cell that literally *contains* the text `"#DIV/0!"`. Branch on it with
 * `v instanceof CellError` and read [`code`](CellError::code) for the exact
 * Excel error string. Never thrown.
 */
export declare class CellError {
  /**
   * The exact Excel error string, e.g. `"#DIV/0!"`, `"#N/A"`, or the
   * Recalc-specific `"#UNSUPPORTED!"` / `"#BLOCKED!"` sentinels.
   */
  get code(): string
}

/**
 * A single "the engine refused to compute this" record, surfaced to Node.
 *
 * One entry per [`xl_engine::Diagnostic`], the cell located by sheet name and
 * 0-based `(row, col)`, a stable machine-readable [`kind`](Diagnostic::kind),
 * and the human-readable message. Field names are identical across all three
 * bindings.
 */
export declare class Diagnostic {
  /** The display name of the sheet the diagnostic occurred on. */
  get sheet(): string
  /** 0-based row index of the offending cell. */
  get row(): number
  /** 0-based column index of the offending cell. */
  get col(): number
  /**
   * Stable category string: one of `"ParseError"`, `"UnknownFunction"`,
   * `"ArityError"`, `"UnsupportedConstruct"`, `"CircularReference"`.
   */
  get kind(): string
  /** Human-readable explanation. */
  get message(): string
}

/**
 * A loaded workbook: parse → dependency graph → recalc, exposed to Node.
 *
 * Obtain one with [`open`] (from a path) or [`open_bytes`] (from a
 * `Buffer`/`Uint8Array`). Wraps an owned [`xl_engine::Engine`].
 *
 * **Threading (v1 limitation, unified surface §4):** a `Workbook` is bound to
 * the JS thread/env that created it and is not shared across Worker threads
 * (each Worker instantiates the addon independently). There is no async
 * surface in M2: [`recalc`](Workbook::recalc) is synchronous and blocks the
 * event loop for its duration.
 */
export declare class Workbook {
  /**
   * Recalculate the whole workbook in dependency order (idempotent).
   *
   * Until this is called, [`value`](Workbook::value) returns the file's
   * cached values (whatever Excel last stored), not values Recalc computed.
   * Refusals known at load time are already visible via
   * [`diagnostics`](Workbook::diagnostics) before recalc.
   */
  recalc(): void
  /** The workbook's sheet display names, in tab order. */
  sheetNames(): Array<string>
  /**
   * The value of a cell by sheet name and **0-based** `(row, col)`.
   *
   * Returns a native JS value per the module's mapping table. A never-
   * populated cell returns `null`. Throws a JS `Error` if `sheet` names no
   * sheet in the workbook.
   *
   * **Before [`recalc`](Workbook::recalc)** this is the file's cached value.
   * Cells Recalc cannot faithfully compute surface as [`CellError`] and via
   * [`diagnostics`](Workbook::diagnostics) — never as a silently-wrong
   * number.
   */
  value(sheet: string, row: number, col: number): number | string | boolean | null | CellError | any[]
  /**
   * Like [`value`](Workbook::value), but locating the cell with an A1 address
   * (e.g. `"B2"`) parsed relative to `sheet`.
   *
   * Throws a JS `Error` for a malformed A1 address or an unknown sheet name.
   */
  cell(sheet: string, a1: string): number | string | boolean | null | CellError | any[]
  /**
   * Every "refused to compute" record known so far, as [`Diagnostic`]
   * objects. Load-time refusals are present immediately after
   * [`open`]/[`open_bytes`]; evaluation-time refusals are added by
   * [`recalc`](Workbook::recalc).
   */
  diagnostics(): Array<Diagnostic>
  /**
   * The spill region anchored at `a1` (the `A1#` surface, RFC-0013 §3), as a
   * row-major 2-D array — or `null` if the addressed cell is not a spill
   * anchor (BC-10: obstructed anchor, spilled-into, plain, or non-formula
   * cell → `null`; a 1×1 dynamic-array anchor → its 1×1 array).
   *
   * Throws a JS `Error` for a malformed A1 address or an unknown sheet name
   * — the same misuse errors as [`cell`](Workbook::cell).
   *
   * Routed through [`Engine::spill_region`](xl_engine::Engine::spill_region),
   * the single read-only anchor→region query (RFC-0013 §3) shared by all
   * three bindings. `Some(Value::Array)` marshals as a row-major 2-D JS array
   * via the canonical [`value_to_node`]; `None` (non-anchor, BC-10) → JS
   * `null`. The engine maintains a live spill-anchor registry (updated on
   * every recalc), so a dynamic-array anchor returns its reconstructed region
   * and a non-anchor returns `null`; spills are compute-only in v1 (queryable
   * here but not written back to the file).
   */
  spillRegion(sheet: string, a1: string): any[] | null
}

/**
 * Open a workbook from a filesystem path. Throws a JS `Error` on any
 * load/parse failure (bad zip, malformed XML, hardening-cap violation, …).
 */
export declare function open(path: string): Workbook

/**
 * Open a workbook from in-memory bytes (the raw `.xlsx`/`.xlsm` zip).
 *
 * Accepts a `Buffer` or a `Uint8Array` (a `Buffer` is a `Uint8Array` subclass
 * — idiom, not divergence, §3.3). Throws a JS `Error` on any load/parse
 * failure.
 */
export declare function openBytes(data: Buffer | Uint8Array): Workbook

/**
 * The assertable surface-version constant (unified surface §1.2c). Integer `1`
 * denotes exactly the operation set of the unified binding API surface
 * (2026-07-15); bumped in lockstep across all bindings on any additive change.
 */
export const SURFACE_VERSION: number
